name: model_test_hooks

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  mason: ^0.1.0-dev.52
  model_test_generator:
    git:
      url: https://github.com/willhlas/model_test_generator.git
      ref: 391946f
